import Head from "next/head";
import Image from "next/image";
import { fetchAPI, getHomeData, getGlobalData } from "../lib/api";
import Layout from "../components/Layout/Layout";
import PhotoShowcase from "../components/UI/PhotoShowcase/PhotoShowcase";
import EventCard from "../components/Events/EventCard";
import classes from "./index.module.scss";

export async function getStaticProps() {
  const [homeData, globalData] = await Promise.all([
    getHomeData(),
    getGlobalData(),
  ]);
  return {
    props: { homeData: homeData, globalData },
    revalidate: 1,
  };
}

export default function Home({ homeData, globalData }) {
  return (
    <>
      {/* <div className={styles.container}> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log("HD: ", homeData)}

      <Layout globalData={globalData}>
        <main className={classes.main}>
          <div className={classes.main__Top}>
            <div
              className={classes.main__Top__Text}
              dangerouslySetInnerHTML={{ __html: homeData.TopText }}
            ></div>
            <div className={classes.main__Top__BG}></div>
            <div className={classes.main__Top__Image}>
              <Image
                src={homeData.TopImage.data.attributes.url}
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
          <section>
            <div className={classes.main__Intro}>
              <div
                className={classes.main__Intro__Text}
                dangerouslySetInnerHTML={{ __html: homeData.IntroText }}
              ></div>
              <div className={classes.main__Intro__Collage}>
                <div
                  className={`${classes.main__Intro__Collage__photo} ${classes.main__Intro__Collage__photo_p1}`}
                >
                  <Image
                    src={homeData.IntroCollage.data[0].attributes.url}
                    layout="fill"
                    objectFit="cover"
                  />
                </div>
                <div
                  className={`${classes.main__Intro__Collage__photo} ${classes.main__Intro__Collage__photo_p2}`}
                >
                  <Image
                    src={homeData.IntroCollage.data[2].attributes.url}
                    layout="fill"
                    objectFit="cover"
                  />
                </div>
                <div
                  className={`${classes.main__Intro__Collage__photo} ${classes.main__Intro__Collage__photo_p3}`}
                >
                  <Image
                    src={homeData.IntroCollage.data[1].attributes.url}
                    layout="fill"
                    objectFit="cover"
                  />
                </div>
              </div>
            </div>
          </section>


            <div className={classes.main__Events}>
              <div className="row">
                <h2 className="u-padding-bottom-medium">Featured Events</h2>
                <div className={classes.main__Events__Group}>
                  {homeData.FeaturedEvents.data.map((event) => (
                    <EventCard event={event} key={event.id} />
                  ))}
                </div>
              </div>
            </div>


          {/* <section> */}
            <PhotoShowcase data={homeData.PhotoShowcase.data} />
          {/* </section> */}
        </main>

        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer> */}
      </Layout>
      {/* </div> */}
    </>
  );
}
